spring:
  application:
    name: assignment

  datasource:
    url: jdbc:mysql://localhost:3306/assignment
    username: hyodongg
    password: ejvhqkel12!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST} # Redis 서버 주소
      port: ${REDIS_PORT} # Redis 포트
      password: ${REDIS_PASSWORD}

  # 캐시 설정
  cache:
    type: redis # 캐시 구현체로 Redis 사용

cache:
  ttl:
    default-ttl: ${CACHE_TTL_DEFAULT:600000}
    article-detail: ${CACHE_TTL_ARTICLE_DETAIL}
    article-list: ${CACHE_TTL_ARTICLE_LIST}

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.cache.interceptor.CacheInterceptor: TRACE



security:
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpired: ${ACCESS_TOKEN_EXPIRED}
    refreshTokenExpired: ${REFRESH_TOKEN_EXPIRED}
  kakao:
    restApiKey: ${KAKAO_REST_API_KEY}
    redirectUri: ${KAKAO_REDIRECT_URI}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs # API 명세서 JSON 경로 설정
  swagger-ui:
    path: /swagger-ui # Swagger UI 접속 경로 (localhost:8080/swagger-ui)
    url: /v3/api-docs # ⭐️ 가장 중요! Swagger에게 읽어올 문서 위치를 강제로 지정
    disable-swagger-default-url: true # 기본 Petstore URL 비활성화
    operations-sorter: method # API 목록을 HTTP Method 순서로 정렬
    display-request-duration: true # 요청 보냈을 때 걸린 시간 표시 (디버깅용)